### ISSUE TITLE
Hello, my virtual machine crashed while running the INET installation.

### ISSUE THREAD

**Issue by qjjasjcdguj** [eniac/MimicNet#4]
Hello, my virtual machine crashed while running the INET installation.

I want to ask if it is due to hardware, and is my memory insufficient?

My virtual machine configuration is Ubuntu 18.04, 4-core CPU, 12GB memory.

What is your computer configuration?

**Comment by qizzz** [comment]
The memory size might be a bit low. We tested MimicNet using the c240g5 machine on CloudLab (http://docs.cloudlab.us/hardware.html), which has the following configuration.

Hardware:
CPU: Two Intel Xeon Silver 4114 10-core CPUs at 2.20 GHz
RAM: 192GB ECC DDR4-2666 Memory
GPU: One NVIDIA 12GB PCI P100 GPU
Disk: One Intel DC S3500 480 GB 6G SATA SSD

Software:
Ubuntu 16.04
CUDA 9.2

**Comment by vinlnx** [comment]
BTW if you're running in a VM, a bigger risk than memory is your maximum virtual disk size.  If it still doesn't work after increasing both, please reopen the issue with a log of the terminal output and any error messages.
