### ISSUE TITLE
Mimicnet vs. Simulator evaluation

### ISSUE THREAD

**Issue by MiquelFerriol** [eniac/MimicNet#5]
Dear developers,
I've been trying to compare the values returned by Mimicnet with the actual values produced by the simulator. I have successfully run the `./run_all` script but could not compare both results, or where they are located.

Is there an easy way to do so? Am I missing something? I have taken a look at the evaluate directory but for me, it is not clear how to execute it. Otherwise, is it possible to obtain these values used to compute the metrics in the paper?

Thank you very much for your time!
Thanks,
Miquel

**Comment by qizzz** [comment]
After running `run_all.sh`, MimicNet simulation result can be found under `simulate/simulate_mimic_<VARIANT>/results/`. `evaluate/` provides scripts to parse the raw traffic file into network performance data of interest.

To simulate a protocol without using MimicNet, directly go to `simulate/simulate_<VARIANT>/` and run `run.sh` with the same parameters as in MimicNet. After running the simulation (the result can be found under `simulate/simulate_<VARIANT>/results/`), go back to the root directory and run `prepare/parse_pdmps.sh <RESULT_DIR> <NUM_CLUSTERS>` to generate the raw traffic file, and then use `evaluate/` scripts to parse the result.

`evaluate/visualize/` provides scripts to compute CDFs and visualize them with gnuplot.
